name: bloc_superpowers
description: "Bloc Superpowers"
version: 0.0.1
homepage: blocsuperpowers.org

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  fast_immutable_collections: ^11.1.0
  collection: ^1.18.0
  connectivity_plus: ">=6.0.3 <8.0.0"
  i18n_extension_core: ^5.0.0
  serverpod_serialization: ^2.5.1
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
