name: bloc_superpowers
description: "Superpowers for your Cubits: Loading and error states, retry, check-internet, debounce, throttle, non-reentrant, fresh, sequential, effects, optimistic functions."
version: 1.0.1
homepage: https://blocsuperpowers.org
repository: https://github.com/marcglasberg/bloc_superpowers
issue_tracker: https://github.com/marcglasberg/bloc_superpowers/issues
documentation: https://blocsuperpowers.org

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  bloc: ^9.2.0
  fast_immutable_collections: ^11.1.0
  collection: ^1.19.1
  connectivity_plus: ">=6.0.3 <8.0.0"
  i18n_extension_core: ^5.0.2
  serverpod_serialization: ^3.2.3
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_bloc: ^9.1.1

flutter:
